### ISSUE TITLE
Some imports not working

### ISSUE THREAD

**Issue by svachmic** [jayantshekhar/strata-2016#1]
Hi, I closely followed all the necessary steps, but I stumbled upon couple errors.

I've downloaded everything as was said, set Scala version to 2.10.6 and this is what I'm getting (screenshot):

![screen shot 2016-05-30 at 14 31 03](https://cloud.githubusercontent.com/assets/1448888/15649639/5363377c-2673-11e6-8262-6e44ad9734fa.png)

**Comment by WhiteFangBuck** [comment]
Hello @svachmic,

Could you check if you have java installed?

**Comment by jayantshekhar** [comment]
@svachmic 

It seems it is not able to find the scala files. Can you:
- Under Project/Properties/Java Build Path
- Check if you have spark-mllib/src/main/scala under source

![image](https://cloud.githubusercontent.com/assets/1664088/15654921/23748cce-2690-11e6-8e66-077d8ebe6ed5.png)

**Comment by jayantshekhar** [comment]
If I remove spark-mllib/src/main/scala, I run in the same error.

Though, I did not have had to explicitly add that folder.

![image](https://cloud.githubusercontent.com/assets/1664088/15654945/60d6cb5e-2690-11e6-8db0-c6bdb03741b7.png)

**Comment by jayantshekhar** [comment]
When I add the folder back, the error goes away:

![image](https://cloud.githubusercontent.com/assets/1664088/15654988/a86530b4-2690-11e6-92c7-d554cf662113.png)

Hope that helps @svachmic

**Comment by svachmic** [comment]
Perfect, thanks a lot @jayantshekhar ! Looking forward to the workshop!

**Comment by jayantshekhar** [comment]
Looking forward to seeing you @svachmic at the workshop!
